#Game Data legend = name, platforms, category, member rating, critic rating
game_data = [['STRAY', ['PLAYSTATION', 'PC'], ['ADVENTURE', 'INDIE'], 84, 86],
             ['MADISON', ['XBOX', 'PLAYSTATION', 'PC', 'NINTENDO SWITCH'], ['ADVENTURE', 'INDIE', 'PUZZLE', 'SIMULATOR'], 'N/A', 80],
             ['THE MORTUARY ASSISTAND', ['PC'], ['ADVENTURE', 'INDIE'], 70, 'N/A'],
             ['SPLATOON 3', ['NINTENDO SWITCH'], ['PLATFORM', 'SHOOTER'], 'N/A', 82],
             ['RETURN TO MONKEY ISLAND', ['PC', 'NINTENDO SWITCH'], ['ADVENTURE', 'PUZZLE'], 90, 91],
             ['TORCHLIGHT 3', ['XBOX', 'PLAYSTATION', 'PC', 'NINTENDO SWITCH'], ['ADVENTURE', 'INDIE', 'ROLE-PLAYING(RPG)'], 49, 66],
             ['CITADEL FORGED WITH FIRE', ['XBOX', 'PLAYSTATION', 'PC'], ['ADVENTURE', 'INDIE', 'ROLE-PLAYING(RPG)'], 50, 50],
             ['CHILDREN OF MORTA', ['XBOX', 'PLAYSTATION', 'PC', 'NINTENDO SWITCH'], ['ADVENTURE', 'INDIE', 'ROLE-PLAYING(RPG)'], 64, 83],
             ['MULTIVERSUS', ['XBOX', 'PLAYSTATION', 'PC'], ['FIGHTING', 'HACK N SLASH'], 71, 76],
             ['CULT OF THE LAMB', ['XBOX', 'PLAYSTATION', 'PC', 'NINTENDO SWITCH'], [], 64, 'N/A'],
             ['TWO POINT CAMPUS', ['XBOX', 'PLAYSTATION', 'PC', 'NINTENDO SWITCH'], ['INDIE', 'SIMULATOR', 'STRATEGY' ], 'N/A', 83],
             ['SAINTS ROW', ['XBOX', 'PLAYSTATION', 'PC', 'NINTENDO SWITCH'], ['ADVENTURE', 'SHOOTER'], 50, 61],
             ['FAR CRY NEW DAWN', ['XBOX', 'PLAYSTATION', 'PC'], ['ADVENTURE', 'SHOOTER'], 67, 72],
             ['CONTRABAND POLICE', ['PC'], ['INDIE', 'SHOOTER', 'SIMULATOR'], 'N/A', 'N/A'],
             ['CALL OF DUTY MOBILE', ['IOS', 'ANDROID'], ['SHOOTER'], 65, 83],
             ['DISNEY DREAMLIGH VALLEY', ['XBOX', 'PLAYSTATION', 'PC', 'NINTENDO SWITCH'], ['ADVENTURE', 'SIMULATOR'], 'N/A', 90],
             ['TINY ROGUES', ['PC'], ['ADVENTURE', 'ARCADE', 'INDIE', 'ROLE-PLAYING(RPG)', 'SHOOTER'], 'N/A', 'N/A']]